// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Card struct {
	ID         string `json:"id"`
	Owner      string `json:"owner"`
	APIID      string `json:"apiID"`
	Cvv        string `json:"cvv"`
	CardNo     string `json:"cardNo"`
	ExpiryDate string `json:"expiryDate"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type NewCard struct {
	Title      string `json:"title"`
	Owner      string `json:"owner"`
	Cvv        string `json:"cvv"`
	CardNo     string `json:"cardNo"`
	APIID      string `json:"apiID"`
	ExpiryDate string `json:"expiryDate"`
}

type NewTransanction struct {
	Card              string `json:"card"`
	Time              string `json:"time"`
	Amount            string `json:"amount"`
	APIID             string `json:"apiID"`
	DebitedOrCredited bool   `json:"debitedOrCredited"`
}

type NewUser struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Transaction struct {
	ID                string `json:"id"`
	APIID             string `json:"apiID"`
	Card              string `json:"card"`
	Time              string `json:"time"`
	Amount            string `json:"amount"`
	DebitedOrCredited bool   `json:"debitedOrCredited"`
}

type User struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Password string `json:"password"`
}
